name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Cambia esto a la versión de Python que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Agrega aquí cualquier otra dependencia que necesites

    - name: Run tests
      run: |
        python -m unittest discover  # Esto ejecuta todas las pruebas unitarias en el directorio